runtime: cs
api_version: go1

handlers:
- url: /10390-Flexcom-4729-2019-03-27.pdf
  static_dir: static/10390-Flexcom-4729-2019-03-27.pdf
  http_headers:
    Access-Control-Allow-Origin: https://github.com/AntoineDoyon/AI_Test/10390-Flexcom-4729-2019-03-27.pdf

